version: "3.9"

services:
  app:
    build: .
    container_name: ecommerce-order-receipt-api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DATABASE: ecommerce_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
